#!/bin/sh

envexists() {
  printenv $@ > /dev/null
  return $?
}

main() {
  cmdline="$@"

  if envexists MEMCHECK; then
    cmdline="$MEMCHECK $cmdline"
  fi

  if $cmdline; then
    echo "($@) [V] Test passed"
  else
    echo "($@) [X] Test failed"
  fi
}

main $@

